services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.env:/var/www/.env
      # Persistir base de datos SQLite
      - ./database:/var/www/database
      # Persistir archivos subidos y logs
      - ./storage:/var/www/storage
      # Montar los certificados SSL del Host (Let's Encrypt) en el contenedor de forma segura
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
